# ECON526: Assignment 2

Jesse Perla, Paul Schrimpf, and Phil Solamine

## Setup

Use the following packages and imports

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy
from numpy.linalg import cond, matrix_rank, norm
from scipy.linalg import inv, solve, det, eig, lu, eigvals
from scipy.linalg import solve_triangular, eigvalsh, cholesky

## Q1.1

Generate a random matrix $A \in \mathbb{R}^{10\times 10}$ and random
vector $b\in\mathbb{R}^{10}$ of uniformly distributed floating points
between 0 and 1. Hint: use `np.random.rand(10, 10)`

and solve $A x = b$ as a linear system with

1.  `scipy.linalg.solve`
2.  `scipy.linalg.inv`

Modify

In [3]:
N = 10
# modify here
A = np.random.rand(10, 10)
b = np.random.rand(10, 1)
scipy.linalg.solve(A, b)

array([[ 2.61535232],
       [ 2.65863419],
       [-0.72255686],
       [ 0.76822251],
       [ 5.34380056],
       [ 0.71939471],
       [-4.48137235],
       [-4.21046578],
       [ 1.78835942],
       [-4.49610567]])

What matrix decomposition would `scipy.linalg.solve` likely use in this
case?

LU Decomposition

## Q1.2

The product of any matrix with its transpose is symmetric. Prove it.
Hint: the definition of symmetric matrix $B$ is if $B = B^T$. Use this
to take the transpose of $B \equiv A^T A$.

(double click to edit your answer)
$\\ B = A^T A \\$
$B^T = (A^T A)^T \\$
$B^T = A^T (A^T)^T \\$
$B^T = A^T A \\$
$B^T = B$

## Q1.3

Using your matrix $A$ from before, construct the symmetric $B = A^T A$.

Verify it is symmetric, and then find out if it is positive definite.
Hint: you will need to use `eigvals` or `eigs`.

In [4]:
# modify here, using A from above
B = A.T @ A
def is_symmetric(A):
    return np.allclose(A, A.T)
print(is_symmetric(B))
print(np.all(eigvals(B) > 0))


True
True


## Q1.4

Now solve the system $B x = b$ using `solve` and `inv`. If the matrix
was shown to be symmetric or positive definite before, then use that in
your solution

In [5]:
# modify here
scipy.linalg.solve(B, b)

array([[-25.86121883],
       [-26.86912226],
       [  4.1084523 ],
       [ -7.04289645],
       [-62.75185589],
       [ -6.9070965 ],
       [ 55.19659893],
       [ 47.57748301],
       [-22.24817795],
       [ 54.49137023]])

## Q2.1

Take the matrix $A \in \mathbb{R}^{100 \times 5}$

Check if it is full rank

In [6]:
# modify here
N = 100
K = 5
A = np.random.rand(N, K)

np.linalg.matrix_rank(A)

5

## Q2.2

Take that previous matrix in Q2.1 and append a new column to it, so that
it is now $\hat{A} \in \mathbb{R}^{100 \times 6}$ such that the matrix
will still have a rank of $5$ and not 6. Hint: lots of ways to append a
vector to a matrix in numpy, including `numpy.column_stack` and
`numpy.concatenate`

In [7]:
# modify here
add_A = np.random.rand(N, 1)
A_hat = np.concatenate((A, add_A), axis=1)

## Q2.3

Take the $A$ and the $\hat{A}$ from before, and form $B = A A^T$ and
$\hat{B} = \hat{A} \hat{A}^T$. What are there ranks?

In [8]:
# modify here
B = A.T @ A
B_hat = A_hat.T @ A_hat
print(np.linalg.matrix_rank(B_hat))
print(np.linalg.matrix_rank(B))

6
5


Could we do a cholesky decomposition of this matrix? Check and/or
explain why not if you can’t

In [9]:
np.linalg.cholesky(B_hat)

array([[5.46999695, 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [4.64508859, 3.4372233 , 0.        , 0.        , 0.        ,
        0.        ],
       [3.70767547, 2.04145827, 3.36322265, 0.        , 0.        ,
        0.        ],
       [3.86884918, 1.65838199, 1.21451181, 3.14383487, 0.        ,
        0.        ],
       [3.83888283, 1.80888291, 0.8688476 , 0.6873875 , 3.18493866,
        0.        ],
       [4.68178631, 1.61620757, 1.88217591, 0.81703958, 0.74523768,
        3.32722945]])

Yes we can

## Q3.1

Take the following $B\in\mathbb{R}^{N\times N}$ symmetric matrix and do
an eigendecomposition (spectral decomposition in this case since
symmetric), and print out the eigenvalues

In [10]:
N = 10
A = 2.0 * np.random.rand(N, N)
B = A.T @ A

# modify here
# Lambda, Q = .... 
Lambda, Q = eig(B)
print(Lambda)

[1.17632766e+02+0.j 8.81265160e+00+0.j 6.32918500e+00+0.j
 5.30987406e+00+0.j 3.95847747e+00+0.j 2.84041919e+00+0.j
 1.90749613e+00+0.j 9.22732389e-02+0.j 8.77557199e-01+0.j
 7.54097660e-01+0.j]


## Q3.2

For your matrix above, calculate its spectral radius

In [11]:
# modify here
def spectral_radius(matrix):
    eigenvalues = np.linalg.eigvals(matrix)
    return np.max(np.abs(eigenvalues))
spectral_radius(B)

117.63276609468775

## Q4.1

Take the vector $\hat{x}_1\in \mathbb{R}^2$

In [12]:
x_hat_1 = np.array([1, 2])

Verify that it is not a unit length vector (i.e. $\|\hat{x}_1\| \neq 1$)
then create a new $x_1$ that is a unit length vector in the same
direction as $\hat{x}_1$ (i.e. $||x_1|| = 1$)

In [15]:
# modify here
# x_1 = ...
x_hat_1_norm = np.square(x_hat_1)
x_hat_1_norm = np.sum(x_hat_1_norm)
x_hat_1_norm = np.sqrt(x_hat_1_norm)

x_1 = x_hat_1 / x_hat_1_norm

## Q4.2

Now find a $x_2$ which is also a unit length vector, but is orthogonal
to $x_1$. Check it with `np.dot(x_1, x_2)` approx 0 and `norm(x_2)`
approx 1. Hint: many ways to do this by hand in $\mathbb{R}^2$ and
fulfill the requirements, such as simple rotations.

In [20]:
# modify here
# x_2 = ...

#transpose not working
# x_2, x_2_triangular = np.linalg.qr(x_1)
# np.dot(x_1, x_2)
# norm(x_2)

x_2 = [x_1[1], -x_1[0]]
print(np.dot(x_1, x_2))
print(norm(x_2))

0.0
0.9999999999999999


## Q4.3

The vectors $x_1$ and $x_2$ are now an orthonormal set. Form the matrix
$Q = \begin{bmatrix} x_1 & | & x_2\end{bmatrix}$ and verify the
condition for orthonormality (i.e. $Q^T Q = I\implies Q^{-1} = Q^T$)

In [21]:
# Q = np.column_stack((x_1, x_2))
# modify here
Q = np.column_stack((x_1, x_2))
Q.T @ Q

array([[ 1.00000000e+00, -1.25949234e-17],
       [-1.25949234e-17,  1.00000000e+00]])

## Q4.4

Create a matrix $A$ such that: 1. $Q$ are its eigenvectors 2. The
spectral radius of $A$ is $1.0$ 3. $A$ is positive definite.

Hint: create a matrix of eigenvalues $\Lambda$ and then do an
eigendecomposition in reverse

In [24]:
# modify here
_lambda = [[1 , 0] , [0 , 0.5]]
A = Q @ _lambda @ Q.T