# ECON526: Assignment 3

Jesse Perla, Paul Schrimpf, and Phil Solamine

## Setup

Feel free to use the following packages (and we have added a few
convenience imports)

In [58]:
import numpy as np
import matplotlib.pyplot as plt
import scipy
from numpy.linalg import cond, matrix_rank, norm
from scipy.linalg import inv, solve, det, eig, lu, eigvals
from scipy.linalg import solve_triangular, eigvalsh, cholesky

## Q1.1

Prove that if you have an eigendecomposition of $A = Q \Lambda Q^{-1}$,
then $A \cdot A = A^2 = Q \Lambda^2 Q^{-1}$ where $\Lambda^2$ is the
componentwise square of the eigenvalues. Hint: use the fact that the $Q$
is orthonormal

(double click to edit your answer)

$A \cdot A = Q \Lambda Q^{-1} Q \Lambda Q^{-1}$ 

$A \cdot A = Q \Lambda I \Lambda Q^{-1}$

$A \cdot A = Q \Lambda^2 Q^{-1}$

## Q1.2

There is nothing special in part 1.1 about taking the square. Just as
you would define the square root of a number $x$ as a $x^{1/2}$ such
that $x^{1/2} \times x^{1/2} = x$, we can do the same thing with a
matrix square root $A^{1/2}$ is such that $A^{1/2} \cdot A^{1/2} = A$.

Use the eigendecomposition and take inspiration from part Q1.1 to find
$A^{1/2}$ for the $A$ given below. Verify that
$A^{1/2} \cdot A^{1/2} \approx A$.

In [59]:
A = np.array([[2, 1], [1, 2]])
# modify here to calculate A^{1/2}, i.e. where A^{1/2} A^{1/2} = A
Lamda , Q = eig(A)
Lamda = np.diag(Lamda)
A_sqrt = Q @ np.sqrt(Lamda) @ inv(Q)

A_sqrt @ A_sqrt

array([[2.+0.j, 1.+0.j],
       [1.+0.j, 2.+0.j]])

## Q1.3

Consider that both $(-2)\times(-2) = 2 \times 2 = 4$. There may be
multiple square roots of a matrix, and many matrices do not have a
square root. For example, For example, the matrix
$A = \begin{bmatrix} 0 & 1 \\ 0 & 0 \end{bmatrix}$ does not have a
square root.

Take this matrix and mention a property of it that suggests why this
matrix looks suspicious and does not have a unique square root or why
the method might fail

In [60]:
A = np.array([[0, 1], [0, 0]])
# modify here, add comments and an explanation on what the problems here would be
Lamda , Q = eig(A)
print(Lamda)

#Because the matrix A is not full rank, the eigenvalues are not unique.

[0.+0.j 0.+0.j]


## Q1.4

Argue that if a matrix is symmetric positive definite then its square
root will also be symmetric, positive definite.

(double click to edit your answer)

$A^{1/2} = Q \Lambda^{1/2} Q^{T}$

$A^{1/2} = (Q \Lambda^{1/2} Q^{T})^T$

$A^{1/2} = (A^{1/2})^T$

Since all eigenvalues in $\Lambda$ are positive, all eigenvalues in $\Lambda^{1/2}$ will also be positive. Therefor, $A^{1/2}$ is positive definite.

## Q2.1

Take a random variable with the multivariate normal distribution

$$
Y \sim N(\mu, \Sigma)
$$

with $\mu \equiv \begin{bmatrix} 0 \\ 1\end{bmatrix}$ and
$\Sigma \equiv \begin{bmatrix} 0.1 & 0.05 \\ 0.05 & 0.1 \end{bmatrix}$

Take 10,000 draws using this distribution. Hint: See
`np.random.multivariate_normal` in the lecture notes.

In [61]:
N = 10000
# modify here
mu = np.array([0,1])
Sigma = np.array([[0.1 , 0.05], [0.05, 0.1]])
Y_draws = 10000

random = np.random.multivariate_normal(mu, Sigma, Y_draws)


## Q2.2

Take the `Y_draws` above, calculate the mean and covariance matrix, and
compare them to $\mu$ and $\Sigma$ to see how close they are. Hint: use
`np.cov(Y_draws, rowvar=False)` to get the covariance matrix. What is a
natural way to compare how close matrices or vectors are?

In [62]:
# modify code here
# make sure to state how you are comparing vectors/matrices

print(np.cov(random, rowvar=False))
print(np.mean(random, axis=0))

[[0.09916962 0.04914868]
 [0.04914868 0.09967011]]
[-4.18487000e-04  1.00152739e+00]


**(double click to add an explanation here)**

One way is to compare each individual element of the matrix to the corresponding element of the other matrix. In this case, the covariance and mean of the draws are very close to the true values.

## Q2.3

A key property of Gaussian random variables is that for any
$Y \sim N(\mu, \Sigma)$ we can write it as a function of a unit
multivariate normal $X \sim N(0, I)$ and a matrix $A$ such that
$Y = \mu + C X$. This is called the Cholesky decomposition of $\Sigma$.

1.  Find the Cholesky of the covariance matrix $\Sigma$, $C$. You can
    use upper or lower Cholesky, but be consistent
2.  Draw the same $N$ number of draws from $X \sim N(0,I)$ as the
    previous parts of Q2
3.  Transform those draws $Y$
4.  Compare the mean and covariance of those transformed $Y$ to $\mu$
    and $\Sigma$ to see how well the transformation did

In [63]:
# modify code here
mu_new = np.array([0 , 0])
Sigma_new = np.array([[1 , 0], [0, 1]])
cholesky = np.linalg.cholesky(Sigma)
random_new = np.random.multivariate_normal(mu_new, Sigma_new, Y_draws)

y = random_new @ cholesky + mu
print(np.mean(y, axis=0))
print(np.cov(y, rowvar=False))

#The mean is roughly the same, but the covariance matrix is different.

[-5.51848679e-04  1.00019021e+00]
[[0.12559936 0.04371376]
 [0.04371376 0.07647029]]


## Q2.4

The same transformation works with the matrix square root. That is, if
$Y \sim N(\mu, \Sigma)$, then $Y = \mu + \Sigma^{1/2} X$ where
$X \sim N(0, I)$ where $\Sigma^{1/2}$ is the matrix square root of
$\Sigma$.

Repeat the Q2.3 using this transformation instead. That is,

1.  Find the square root of the covariance matrix $\Sigma$,
    $\Sigma^{1/2}$. Hint: You can do this yourself using previous
    sections, use the `scipy` function `scipy.linalg.sqrtm` or use the
    scipy function `scipy.linalg.matrix_power` with the argument `0.5`.
2.  Draw the same $N$ number of draws from $X \sim N(0,I)$ as the
    previous parts of Q2
3.  Transform those draws to form $Y$ samples
4.  Compare the mean and covariance of those transformed $Y$ to $\mu$
    and $\Sigma$ to see how well the transformation did

In [64]:
# modify code here
cov_sqrt = scipy.linalg.sqrtm(Sigma)
random_last = np.random.multivariate_normal(mu_new, Sigma_new, Y_draws)
y_last = random_last @ cov_sqrt + mu

print(np.mean(y_last, axis=0))
print(np.cov(y_last, rowvar=False))

#The mean is roughly the same, the covariance matrix is also roughly the same.

[-0.0013267  1.0023097]
[[0.10252995 0.05208497]
 [0.05208497 0.09994235]]


## Q3.1

Take a new mean $\mu$ and covariance matrix, $\Sigma$. You want to do
the same thing as previous examples (i.e., find a matrix, $A$ such that
$Y = \mu + A X$ for $X \sim N(0,I)$).

Take the matrix below, its eigenvalues, and the results of calling
Cholesky. Explain why you probably shouldn’t be using it in this case.

In [65]:
mu = np.array([0, 1, 1])
Sigma = np.array([
    [26, 21, 6],
    [21, 17, 5],
    [6, 5, 2]
]) / 30.0
C = scipy.linalg.cholesky(Sigma, lower=True)
print(C)
print(f"Eigenvalues(Sigma) = {eigvalsh(Sigma)}")

[[9.30949336e-01 0.00000000e+00 0.00000000e+00]
 [7.51920618e-01 3.58057437e-02 0.00000000e+00]
 [2.14834462e-01 1.43222975e-01 5.83100164e-08]]
Eigenvalues(Sigma) = [-9.98809413e-17  1.95131000e-02  1.48048690e+00]


**(double click to add an explanation here)**

Since there exists one eigenvalue that is very close to 0, the matrix is not positive definite, meaning that the cholesky decomposition will result in numerical errors.

## Q3.2

The Cholesky is suspicious, but what about the matrix square root?

In [66]:
Sigma_sqrt = scipy.linalg.sqrtm(Sigma)
print(f"Sigma^-1 = \n{Sigma_sqrt}")
print(f"Sigma^-1 real only = \n{np.real(Sigma_sqrt)}")

Sigma^-1 = 
[[0.7208559  0.57388853 0.13298645]
 [0.57388853 0.4659534  0.14214798]
 [0.13298645 0.14214798 0.16963261]]
Sigma^-1 real only = 
[[0.7208559  0.57388853 0.13298645]
 [0.57388853 0.4659534  0.14214798]
 [0.13298645 0.14214798 0.16963261]]


Any comments on whether this would be a reasonable way to transform the
random variable into a $Y = \mu + \Sigma^{-1} X$ for $X \sim N(0,I)$?

**(double click to add an explanation here)**

Given the fact that scipy.linalg.sqrtm uses a spectral decomposition, the existance of a 0 eigenvalue will not affect the resulting matrix square root. Therefore, this is a reasonable way to obtain the matrix square root. Hence, this value can be used in the transformation.

## Q3.3

Your friend suggests trying an SVD of the covariance matrix, which is
always defined. Here are the results for $U S V^T = \Sigma$,

In [67]:
U, S, Vh = scipy.linalg.svd(Sigma) # returns V' not V
print(f"U =\n {U}")
print(f"S =\n {S}")
print(f"V' =\n {Vh}")

U =
 [[-0.76451208  0.26337697  0.58834841]
 [-0.61865349 -0.04339637 -0.78446454]
 [-0.18107771 -0.96371641  0.19611614]]
S =
 [1.48048690e+00 1.95131000e-02 2.83470951e-17]
V' =
 [[-0.76451208 -0.61865349 -0.18107771]
 [ 0.26337697 -0.04339637 -0.96371641]
 [ 0.58834841 -0.78446454  0.19611614]]


Your friend then shows you the following

In [68]:
U_truncated = U[:, :2] # truncating to only use the first two columns
S_truncated = np.diag(np.sqrt(S[:2])) # first two singular values
A = U_truncated @ S_truncated # using first two singular values
print(f"shape(A) = {A.shape}")
print(f"A =\n{A}")
print(f"A @ A.T =\n{A @ A.T}")
print(f"||A A' - Sigma|| = {norm(A @ A.T - Sigma)}")

shape(A) = (3, 2)
A =
[[-0.93022207  0.03679094]
 [-0.75274824 -0.00606201]
 [-0.22032678 -0.13462087]]
A @ A.T =
[[0.86666667 0.7        0.2       ]
 [0.7        0.56666667 0.16666667]
 [0.2        0.16666667 0.06666667]]
||A A' - Sigma|| = 1.1664773918553167e-15


Can you explain why this is a great observation and how it might be
useful for transforming the random variable $Y = \mu + A \hat{X}$ for
some unit normal $\hat{X}$?

**(double click to add an explanation here)**

This means that $A$ has preserved the properties of the initial $US$ from the SVD decomposition. Meanins that $A$ can be used to trasnfrom the random variable $Y = \mu + A \hat{X}$ for some unit normal $\hat{X}$.

The fact that $A @ A^{T}$ has the same norm as $\Sigma$ means that it has the same variability as $\Sigma$. All this while reducing the diemnsionality of the problem.

## Q3.4

Finally, your friend uses this to generate a bunch of random values to
check if the random variable works relative to the original and compares
the sqrt version to the new one

In [69]:
N = 100000
Y_draws = np.random.multivariate_normal(mu,Sigma, size=N) # unit normal
X_draws = np.random.multivariate_normal(np.zeros(3), np.eye(3), size=N) # unit normal
Y_draws_sqrt = mu + X_draws @ Sigma_sqrt.T # sqrt version
X_hat_draws = np.random.multivariate_normal(np.zeros(2), np.eye(2), size=N) # unit normal
Y_draws_hat = mu + X_hat_draws @ A.T # Using the A from the SVD
print(f"||mean(Y_draws) - mu|| = {norm(np.mean(Y_draws, axis=0) - mu)}")
print(f"||mean(Y_draws_sqrt) - mu|| = {norm(np.mean(Y_draws_sqrt, axis=0) - mu)}")
print(f"||mean(Y_draws_hat) - mu|| = {norm(np.mean(Y_draws_hat, axis=0) - mu)}")
print(f"||cov(Y_draws) - Sigma|| = {norm(np.cov(Y_draws, rowvar=False) - Sigma)}")
print(f"||cov(Y_draws_sqrt) - Sigma|| = {norm(np.cov(Y_draws_sqrt, rowvar=False) - Sigma)}")
print(f"||cov(Y_draws_hat) - Sigma|| = {norm(np.cov(Y_draws_hat, rowvar=False) - Sigma)}")

||mean(Y_draws) - mu|| = 0.0037134248975424175
||mean(Y_draws_sqrt) - mu|| = 0.00903844796459746
||mean(Y_draws_hat) - mu|| = 0.005684248334399677
||cov(Y_draws) - Sigma|| = 0.006626152448963826
||cov(Y_draws_sqrt) - Sigma|| = 0.0066134113861411065
||cov(Y_draws_hat) - Sigma|| = 0.0006796979412422555


This worked great. In fact, simulating with the new processes seems
almost better than directly using the $Y$ but your friend is confused.
When they simulated `Y_draws` and `Y_draws_sqrt` they were drawing
3-dimensional random normals, but when they did `Y_draws_hat` it was
only 2-dimensional. How can this be and still deliver the same results?
Explain it to your friend.

**(double click to add an explanation here)**

The reason why this works is because the matrix $A$ is a projection matrix. This means that the resulting matrix $\hat{Y}$ will be a projection of the original $Y$ onto a lower dimensional space. This means that the resulting $\hat{Y}$ will have the same variability as the original $Y$ but will have a lower dimensionality.